version: '3.9'

services:
  api:
    build: .
    container_name: fleetrack-api
    restart: unless-stopped
    working_dir: /app
    command: npm run dev
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    volumes:
      - .:/app      # monte ton code
      - node_modules:/app/node_modules  # empêche l'écrasement dans le container

    networks:
      - fleetrack-network

  mongodb:
    image: mongo:6
    container_name: fleetrack-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fleetrack-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: fleetrack-mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    networks:
      - fleetrack-network

networks:
  fleetrack-network:

volumes:
  mongo-data:
  node_modules:
